// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	"context"
	"hotgo/api/api/ipmaker/v1/user"
	"hotgo/internal/library/contexts"
	"hotgo/internal/model/input/appin"
	"hotgo/internal/service/ipmaker"

	"github.com/gogf/gf/v2/errors/gerror"
	"google.golang.org/api/idtoken"
	"github.com/gogf/gf/v2/frame/g"
)

// User C端用户控制器
var User = cUser{}

type cUser struct{}

// GoogleLogin Google登录
func (c *cUser) GoogleLogin(ctx context.Context, req *v1.GoogleLoginReq) (res *v1.GoogleLoginRes, err error) {
	// 从配置中获取Google Client ID
	googleClientID, err := g.Cfg().Get(ctx, "google.clientID")
	if err != nil {
		return nil, gerror.New("Failed to get Google Client ID from config")
	}

	payload, err := idtoken.Validate(ctx, req.Credential, googleClientID.String())
	if err != nil {
		return nil, gerror.Wrap(err, "Invalid Google credential")
	}

	// 从payload中提取用户信息
	email := payload.Claims["email"].(string)
	name := payload.Claims["name"].(string)
	avatar := payload.Claims["picture"].(string)

	// 使用email查找或创建用户
	tokenString, user, err := ipmaker.AppUser().LoginOrRegisterByEmailForGoogle(ctx, &appin.UserLoginOrRegisterByEmailInp{
		Email:    email,
		Nickname: name,
		Avatar:   avatar,
	})

	if err != nil {
		return nil, err
	}

	res = &v1.GoogleLoginRes{
		Token:     tokenString,
		ExpiresAt: user.UpdatedAt.Unix(),
		UserInfo: v1.LoginUserInfo{
			Id:       user.Id,
			Username: user.Username,
			Nickname: user.Nickname,
			Avatar:   user.Avatar,
			Mobile:   user.Mobile,
			Email:    user.Email,
		},
	}
	return
}

// EmailLogin 邮箱登录
func (c *cUser) EmailLogin(ctx context.Context, req *v1.EmailLoginReq) (res *v1.EmailLoginRes, err error) {
	tokenString, user, err := ipmaker.AppUser().LoginOrRegisterByEmail(ctx, &appin.UserEmailLoginInp{
		Email:    req.Email,
		Password: req.Password,
	})

	if err != nil {
		return
	}

	res = &v1.EmailLoginRes{
		Token:     tokenString,
		ExpiresAt: user.UpdatedAt,
		UserInfo: v1.LoginUserInfo{
			Id:       user.Id,
			Username: user.Username,
			Nickname: user.Nickname,
			Avatar:   user.Avatar,
			Mobile:   user.Mobile,
			Email:    user.Email,
		},
	}
	return
}

// Register 用户注册
func (c *cUser) Register(ctx context.Context, req *v1.RegisterReq) (res *v1.RegisterRes, err error) {
	userId, err := ipmaker.AppUser().Register(ctx, &appin.UserRegisterInp{
		Username: req.Username,
		Password: req.Password,
		Mobile:   req.Mobile,
		Email:    req.Email,
	})

	if err != nil {
		return
	}

	res = &v1.RegisterRes{
		UserId: userId,
	}
	return
}

// Login 用户登录
func (c *cUser) Login(ctx context.Context, req *v1.LoginReq) (res *v1.LoginRes, err error) {
	tokenString, user, err := ipmaker.AppUser().Login(ctx, &appin.UserLoginInp{
		Username: req.Username,
		Password: req.Password,
	})

	if err != nil {
		return
	}

	res = &v1.LoginRes{
		Token:     tokenString,
		ExpiresAt: user.UpdatedAt,
		UserInfo: v1.LoginUserInfo{
			Id:       user.Id,
			Username: user.Username,
			Nickname: user.Nickname,
			Avatar:   user.Avatar,
			Mobile:   user.Mobile,
			Email:    user.Email,
		},
	}
	return
}

// Info 获取用户信息
func (c *cUser) Info(ctx context.Context, req *v1.InfoReq) (res *v1.InfoRes, err error) {
	userId := contexts.GetUserId(ctx)
	if userId <= 0 {
		err = gerror.New("用户未登录")
		return
	}

	user, err := ipmaker.AppUser().GetUserInfo(ctx, userId)
	if err != nil {
		return
	}

	res = &v1.InfoRes{
		Id:          user.Id,
		Username:    user.Username,
		Nickname:    user.Nickname,
		Avatar:      user.Avatar,
		Mobile:      user.Mobile,
		Email:       user.Email,
		Sex:         user.Sex,
		Birthday:    user.Birthday,
		LastLoginAt: user.LastLoginAt,
		LastLoginIp: user.LastLoginIp,
		Status:      user.Status,
		CreatedAt:   user.CreatedAt,
		UpdatedAt:   user.UpdatedAt,
	}
	return
}

// Update 更新用户信息
func (c *cUser) Update(ctx context.Context, req *v1.UpdateReq) (res *v1.UpdateRes, err error) {
	userId := contexts.GetUserId(ctx)
	if userId <= 0 {
		err = gerror.New("用户未登录")
		return
	}

	err = ipmaker.AppUser().UpdateProfile(ctx, userId, &appin.UserUpdateProfileInp{
		Nickname: req.Nickname,
		Avatar:   req.Avatar,
		Sex:      req.Sex,
		Birthday: req.Birthday,
	})

	if err != nil {
		return
	}

	res = &v1.UpdateRes{}
	return
}

// Logout 退出登录
func (c *cUser) Logout(ctx context.Context, req *v1.LogoutReq) (res *v1.LogoutRes, err error) {
	err = ipmaker.AppUser().Logout(ctx)
	if err != nil {
		return
	}
	res = &v1.LogoutRes{}
	return
}
