// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package member

type cMember struct{}

var Member = cMember{}

// GoogleLogin 谷歌登录
//func (c *cMember) GoogleLogin(ctx context.Context, req *v1.MemberGoogleLoginReq) (res *v1.MemberGoogleLoginRes, err error) {
//	res, err = service.Member().GoogleLogin(ctx, req)
//	return
//}
