// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// ipDao is the data access object for the table hg_ip.
// You can define custom methods on it to extend its functionality as needed.
type ipDao struct {
	*internal.IpDao
}

var (
	// Ip is a globally accessible object for table hg_ip operations.
	Ip = ipDao{internal.NewIpDao()}
)

// Add your custom methods and functionality below.
