// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// storyDao is the data access object for the table hg_story.
// You can define custom methods on it to extend its functionality as needed.
type storyDao struct {
	*internal.StoryDao
}

var (
	// Story is a globally accessible object for table hg_story operations.
	Story = storyDao{internal.NewStoryDao()}
)

// Add your custom methods and functionality below.
